In [3]:
# import sympy 
from sympy import *

M = Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]) 
print("Matrix : {} ".format(M)) 

# Use sympy.rref() method 
M_rref = M.rref() 
	
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref)) 


Matrix : Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0,   1,   3],
[0, 1, 2/3, 1/3],
[0, 0,   0,   0]]), (0, 1))


In [5]:
import numpy as np

def modinv(n, mod):
  '''
  Lazily finds the multiplicative inverse of n modulo mod.
  '''
  for x in xrange(1, mod):
    if (n * x) % mod == 1: return x
  else:
    raise ArithmeticError('%i has no multiplicative inverse modulo %i.' % (n, mod))

def firstnonzero(row):
  '''
  Finds the index of the first non-zero element of the row.
  '''
  for i, r in enumerate(row):
    if r != 0: return i
  else:
    raise Exception('No non-zeros elements found.')

def swaprows(M, i, j):
  '''
  Swaps rows i and j of the matrix M.
  '''
  M[i], M[j] = M[j], M[i]

def subrow(M, i):
  '''
  Subtracts row i from each other row in the matrix M.
  Assumes that the first non-zero element of i is a 1.
  '''
  f = firstnonzero(M[i])
  for j in xrange(M.shape[0]):
    if i == j: continue
    M[j] -= M[j,f] * M[i]

def normrow(M, i, mod):
  '''
  Normalizes row i of the matrix M such that the first non-zero element is 1.
  '''
  f = firstnonzero(M[i])
  M[i] *= modinv(M[i,f], mod)
  M[i] %= mod
    
def modrref(M, mod):
  '''
  Computes the row-reduced echelon form of the matrix M modulo mod.
  '''
  r = 0
  while r < M.shape[0]:
    # Ignore non-zero rows.
    try: f = firstnonzero(M[r])
    except:
      r += 1
      continue
    
    # Rule 1: Swap with the row above if out of order.
    if r > 0:
      swap = False
      try: g = firstnonzero(M[r - 1])
      except: swap = True
      if swap:
        swaprows(M, r, r - 1)
        continue
    
    # Rule 2: Normalize each row
    normrow(M, r, mod)
    
    # Rule 3: Subtract it from the others
    subrow(M, r)
    r += 1
  return M

def matmodinv(M, mod):
  '''
  Computes the multiplicative inverse of M modulo mod.
  '''
  assert M.shape[0] == M.shape[1]
  I = np.identity(M.shape[0], M.dtype)
  N = np.concatenate((M, I), axis = 1)
  modrref(N, mod)
  M = N[:,M.shape[0]:] % mod

In [7]:
import numpy 
E = numpy.random.random_integers(0, 100, (5, 3))
I = numpy.eye(5)

EstackI = numpy.hstack((E,I))
EstackI = EstackI%2

matrix = EstackI

def addRowsMod2(first, second):
    return [((x + y) % 2) for x, y in zip(first, second)]

numColsE = E.shape[1]  # the number of columns in E

def rowReduceStep(col, matrix):
    selectedRow = -1
    numRows = len(matrix)
    for rowIndex in range(numRows):
        row = list(matrix[rowIndex])
        if row[col] == 1:
            selectedRow = rowIndex
            break

    if selectedRow != -1:
        for i in range(selectedRow + 1, numRows):
            if matrix[i][col] == 1:
                matrix[i] = addRowsMod2(matrix[i], matrix[selectedRow])

    newMatrix = []
    for i in range(numRows):
        if i != selectedRow:
            newMatrix += [matrix[i]]
    return (newMatrix, selectedRow)

for col in range(numColsE):
    result = rowReduceStep(col, matrix)
    matrix = result[0]

finalMat = matrix

C:\Users\dell\AppData\Local\Temp\ipykernel_6432\2090129888.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  E = numpy.random.random_integers(0, 100, (5, 3))


In [10]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [1, 0, 1, 1],
    [0, 1, 0, 1],
    [1, 1, 1, 0]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)


Reduced Row Echelon Form (modulo 2):
[[1 0 1 1]
 [0 1 0 1]
 [0 0 0 0]]


In [11]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [1, 0, 0, 1, 0, 1, 0, 1],
    [0, 1, 1, 0, 0, 1, 0, 1],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [0, 0, 1, 1, 0, 0, 1, 1 ]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)


Reduced Row Echelon Form (modulo 2):
[[1 0 0 1 0 1 0 1]
 [0 1 0 1 0 1 1 0]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 0 0 0 0]]


In [12]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1],
    [0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
    [0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1],
    [1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
    [1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)


Reduced Row Echelon Form (modulo 2):
[[1 0 0 0 0 1 0 0 0 1 0 1]
 [0 1 0 0 0 1 1 0 0 1 1 1]
 [0 0 1 0 0 1 1 1 0 1 1 0]
 [0 0 0 1 0 0 1 1 0 1 0 0]
 [0 0 0 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 1 1 1 1]]


In [13]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1],
    [0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)


Reduced Row Echelon Form (modulo 2):
[[1 0 0 0 0 0 0 1 0 1 1 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 1 1 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 1 0 1]
 [0 0 0 1 0 0 0 0 0 1 0 1 1 0]
 [0 0 0 0 1 0 0 0 1 1 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 0 0 1 0 1 1 0]]


In [1]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1],
    [0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1],
    [0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0],
    [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0],
    [1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
    [1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)


Reduced Row Echelon Form (modulo 2):
[[1 0 0 0 0 0 0 0 1 1 1 0]
 [0 1 0 0 0 0 0 1 1 1 0 0]
 [0 0 1 0 0 0 1 1 1 0 0 0]
 [0 0 0 1 0 0 1 1 0 0 0 1]
 [0 0 0 0 1 0 1 0 0 0 1 1]
 [0 0 0 0 0 1 0 0 0 1 1 1]]


In [2]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1],
    [0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0],
    [0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0],
    [1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
    [1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)



Reduced Row Echelon Form (modulo 2):
[[1 0 0 1 0 1 1 0 0 0 0 0 0 0]
 [0 1 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 0 1 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 1 1]]


In [4]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1],
    [0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0],
    [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
    [0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1],
    [1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1],
    [0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)


Reduced Row Echelon Form (modulo 2):
[[1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 1 1 0 1 0 1 0]
 [0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0]
 [0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1]
 [0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1]]


In [1]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1],
    [0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0],
    [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
    [0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1],
    [1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1],
    [0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)


Reduced Row Echelon Form (modulo 2):
[[1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 1 1 0 1 0 1 0]
 [0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0]
 [0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1]
 [0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1]]


In [2]:
import numpy as np

def mod2_rref(matrix):
    # Convert the matrix to numpy array
    matrix = np.array(matrix, dtype=int)

    # Perform Gaussian elimination
    num_rows, num_cols = matrix.shape
    pivot_row = 0

    for col in range(num_cols):
        # Find a non-zero entry in the current column
        non_zero_row = np.argmax(matrix[pivot_row:, col] != 0) + pivot_row

        if matrix[non_zero_row, col] == 0:
            # If no non-zero entry is found, move to the next column
            continue

        # Swap rows to bring the non-zero entry to the pivot position
        matrix[[pivot_row, non_zero_row]] = matrix[[non_zero_row, pivot_row]]

        # Eliminate other entries in the current column
        for i in range(num_rows):
            if i != pivot_row and matrix[i, col] != 0:
                matrix[i] = (matrix[i] + matrix[pivot_row]) % 2

        # Move to the next pivot row
        pivot_row += 1

        if pivot_row == num_rows:
            break

    return matrix

# Example usage:
matrix = [
    [0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1],
    [0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1],
    [1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1],
    [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1],
    [0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0]
]

rref_matrix = mod2_rref(matrix)
print("Reduced Row Echelon Form (modulo 2):")
print(rref_matrix)



Reduced Row Echelon Form (modulo 2):
[[1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 0 1 1 1 1 0 1 1 0 1]
 [0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 1]]
